# Site settings 配置站点
title: 'Lynn Yang'
description: 'blog'
keywords: 'Lynn Yang, Liling Yang, miss1'
url: 'https://miss1.github.io/' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  Introduction: '/'
  Experience: '/experience/'
  Code: '/codeLink/'

# 博主
author: true
name: 'Liling Yang'
NickName: 'Liling'
webtitle: 'Liling'
bio: 'yes!'
about: true
aboutyou: 'Hey, this is Liling! I''m a software engineer. Recently, I earned my master''s degree in computer science 
and am looking forward to starting a new journey in my career.'
interest1: 'I enjoy hiking and playing video games. If you think that Zelda: Breath of the Wild is one of the best games in the world, then you are my friend~'
interest2: 'If you play Animal Crossing, welcome to visit my island: DA-7213-8641-4226'
portraits: '/assets/profile.jpg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['mail', 'github', 'linkedin', 'leetcode']
  mail: 'mailto:yangll2525@163.com'
  github: 'https://github.com/miss1'
  linkedin: 'https://www.linkedin.com/in/liling-yang'
  leetcode: 'https://leetcode.com/miss1/'

# since
footer:
  since: 2017

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
# social-share: true
# social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: ''
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
